#!/data/data/com.termux/files/usr/bin/bash

## Author    : Technocyber
## Instagram : @Technocyber.sh
## Github    : @Technocyber

## script to make termux cool

## ANSI Colors (FG & BG)
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
DEFAULT_FG="$(printf '\033[39m')"  DEFAULT_BG="$(printf '\033[49m')"

## Directories
PREFIX='/data/data/com.termux/files/usr'
TERMUX_DIR="$HOME/.termux"
DIR="$(pwd)"

## Banner
banner () {
    clear
    echo " "
printf "\e[0m\n"
printf "\e[0m                                                    \e[0m\n"
printf "\e[0m                                                    \e[0m\n"
printf "\e[0m                    \e[38;5;214m▄▄\e[48;5;214m█\e[48;5;179m▀\e[48;5;233m▀\e[0m                \e[38;5;214m▀\e[48;5;214m██\e[48;5;233m▄▄\e[0m                \e[0m\n"
printf "\e[0m                   \e[38;5;208;48;5;215m▄\e[48;5;214m▄\e[48;5;208m█\e[38;5;172;48;5;233m▀\e[0m                    \e[38;5;208;48;5;237m▀\e[48;5;214m▄▄\e[38;5;178m▀\e[0m               \e[0m\n"
printf "\e[0m                  \e[38;5;166;48;5;173m▄\e[38;5;208;48;5;208m█▀▀\e[0m                      \e[38;5;208;48;5;208m█▀\e[38;5;166m▄\e[38;5;52;48;5;131m▀\e[0m              \e[0m\n"
printf "\e[0m                  \e[38;5;16m▀\e[38;5;166;48;5;166m \e[38;5;202m▀\e[48;5;202m█\e[48;5;166m▀\e[38;5;124;48;5;233m▄\e[38;5;202m▄\e[38;5;16;48;5;131m▀\e[0m   \e[38;5;208m▄▄▄▄▄▄▄▄\e[0m   \e[38;5;130m▄\e[38;5;202m▄\e[38;5;124m▄\e[48;5;202m▄\e[38;5;202m█\e[48;5;166m▀\e[38;5;166m \e[0m               \e[0m\n"
printf "\e[0m                    \e[38;5;124;48;5;52m▀\e[48;5;124m█\e[38;5;88;48;5;167m▀\e[38;5;124;48;5;202m▄▄\e[38;5;202m  \e[38;5;124m▄\e[38;5;166;48;5;166m \e[38;5;160;48;5;208m▄\e[38;5;202;48;5;202m      \e[38;5;160;48;5;208m▄\e[38;5;166;48;5;166m▄\e[38;5;124;48;5;202m▄\e[38;5;202m  \e[38;5;124m▄▄\e[38;5;88;48;5;166m▀\e[38;5;124;48;5;124m█\e[48;5;234m▀\e[0m                \e[0m\n"
printf "\e[0m                    \e[38;5;131m▄\e[38;5;167m▄\e[38;5;124;48;5;173m▀\e[38;5;166;48;5;124m▄\e[38;5;160;48;5;160m█\e[38;5;124m▀\e[38;5;88m▀\e[48;5;124m▀\e[38;5;202;48;5;202m \e[38;5;124;48;5;203m▄\e[48;5;124m█\e[48;5;202m▄\e[38;5;196m▄▄\e[38;5;124m▄\e[38;5;160;48;5;160m█\e[38;5;202;48;5;202m▀ \e[38;5;88;48;5;124m▀\e[48;5;160m▀\e[38;5;124m▀\e[38;5;160m█\e[38;5;52;48;5;167m▀\e[38;5;124;48;5;173m▀\e[38;5;131;48;5;233m▄\e[38;5;167m▄\e[0m                \e[0m\n"
printf "\e[0m                     \e[38;5;16;48;5;160m▄\e[38;5;124;48;5;124m \e[48;5;160m▀\e[48;5;124m▀▀\e[48;5;88m▀\e[38;5;88;48;5;161m▀\e[38;5;124;48;5;232m▀\e[48;5;124m█\e[38;5;160;48;5;160m \e[38;5;203m▀\e[38;5;124;48;5;124m▀\e[48;5;88m▀\e[38;5;166;48;5;160m▀\e[38;5;160m \e[38;5;124;48;5;202m▄\e[38;5;166;48;5;233m▀\e[38;5;88;48;5;161m▀\e[38;5;124;48;5;88m▀\e[48;5;124m▀▀\e[48;5;160m▀\e[38;5;88m▀\e[38;5;16m▄\e[0m                 \e[0m\n"
printf "\e[0m                       \e[38;5;88m▀▀\e[38;5;52m▀\e[48;5;232m▀\e[38;5;125;48;5;125m█ \e[38;5;232m▀\e[38;5;88;48;5;53m▀\e[38;5;160;48;5;124m▄\e[48;5;202m▄▄\e[38;5;124;48;5;160m▄\e[38;5;52;48;5;124m▄\e[38;5;16;48;5;125m▀\e[38;5;125m █\e[38;5;52;48;5;233m▀▀\e[38;5;88m▀▀\e[0m                   \e[0m\n"
printf "\e[0m                            \e[38;5;53;48;5;126m▄\e[38;5;125;48;5;125m▄\e[48;5;89m▀\e[48;5;125m \e[38;5;161;48;5;161m  \e[38;5;125;48;5;125m \e[48;5;89m▀\e[48;5;125m▄\e[38;5;89;48;5;89m▀\e[0m                        \e[0m\n"
printf "\e[0m                             \e[38;5;89;48;5;53m▀\e[38;5;127m▄\e[38;5;53m▀\e[38;5;90;48;5;90m  \e[38;5;89;48;5;53m▀\e[38;5;127m▄\e[38;5;89m▀\e[0m                         \e[0m\n"
printf "\e[0m                             \e[38;5;91;48;5;55m▀\e[48;5;17m▀\e[38;5;19;48;5;134m▄\e[48;5;56m▄▄\e[48;5;134m▄\e[38;5;90;48;5;17m▀\e[38;5;91;48;5;55m▀\e[0m                         \e[0m\n"
printf "\e[0m                              \e[38;5;18;48;5;17m▀\e[48;5;24m▀\e[48;5;25m▀▀\e[48;5;18m▀\e[48;5;17m▀\e[0m                          \e[0m\n"
printf "\e[0m                                                    \e[0m\n"
printf "\e[0m
printf "\e[0m\n"  
  echo "
    ${BLUE}┌──────────────────────────────────────────────────┐
    ${BLUE}│${RED}░▀█▀░█▀▀░█▀▄░█▄█░█░█░█░█${ORANGE}░░░░░${GREEN}█▀▀░▀█▀░█░█░█░░░█▀▀░░${BLUE}│
    ${BLUE}│${RED}░░█░░█▀▀░█▀▄░█░█░█░█░▄▀▄${ORANGE}░▄▄▄${RED}░${GREEN}▀▀█░░█░░░█░░█░░░█▀▀░░${BLUE}│
    ${BLUE}│${RED}░░▀░░▀▀▀░▀░▀░▀░▀░▀▀▀░▀░▀${ORANGE}░░░░░${GREEN}▀▀▀░░▀░░░▀░░▀▀▀░▀▀▀░░${BLUE}│
    ${BLUE}└──────────────────────────────────────────────────┘
    ${BLUE}[${RED}*${BLUE}] ${ORANGE}By- Aditya Shakya ${RED}//${ORANGE} adi1090x"
}

## Script Termination
exit_on_signal_SIGINT () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script interrupted." 2>&1; echo; reset_color; }
    exit 0
}

exit_on_signal_SIGTERM () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script terminated." 2>&1; echo; reset_color; }
    exit 0
}

trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM

## Reset terminal colors
reset_color() {
	tput sgr0   # reset attributes
	tput op     # reset color
    return
}

## Prerequisite
prerequisite() {
	{ echo; echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Installing Dependencies..."${CYAN}; echo; }
	if [[ (-f $PREFIX/bin/wget) && (-f $PREFIX/bin/tput) ]]; then
		{ echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Dependencies are already Installed!"; }
	else
		{ pkg update -y; pkg install -y wget ncurses-utils; }
		(type -p wget tput &> /dev/null) && { echo; echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Dependencies are succesfully installed!"; } || { echo; echo "    ${BLUE}[${RED}!${BLUE}] ${RED}Error Occured, failed to install dependencies."; echo; reset_color; exit 1; }
	fi
}

## Install termux-style
install_tstyle () {
	echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Installing termux-style..."
	# Delete old files
	if [[ (-L $PREFIX/bin/termux-style) && (-d $PREFIX/share/termux-style) ]]; then
		echo "    ${BLUE}[${RED}*${BLUE}] ${RED}Deleting files from previous installation..."${BLUE}
		{ rm -r $PREFIX/bin/termux-style $PREFIX/share/termux-style; echo; }
	fi
	# termux config dir
	if [[ ! -d $TERMUX_DIR ]]; then
		mkdir $TERMUX_DIR
	else
		cp -r $TERMUX_DIR{,.backup}
	fi
	# Coping files
	{ echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Coping files in ${GREEN}$PREFIX/share ${ORANGE}directory..."${BLUE}; }
	{ mkdir $PREFIX/share/termux-style; cp -r $DIR/colors $PREFIX/share/termux-style; cp -r $DIR/fonts $PREFIX/share/termux-style; cp -r $DIR/tstyle $PREFIX/share/termux-style; }
	{ chmod +x $PREFIX/share/termux-style/tstyle; ln -s $PREFIX/share/termux-style/tstyle $PREFIX/bin/termux-style; }

	# Verify files 
	if [[ (-L $PREFIX/bin/termux-style) && (-d $PREFIX/share/termux-style) ]]; then
		{ echo; echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Successfully Installed."; }
		{ echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Now You Can Run This Program By Just typing ${MAGENTA}termux-style${GREEN}."; echo; }
		{ reset_color; exit 0; }
	else
		{ echo "    ${BLUE}[${RED}!${BLUE}] ${RED}Error Occured."; echo; reset_color; exit 1; }
	fi
}

## Main
main () {
	banner
	prerequisite
	# Check for previous installation
	if [[ (-L $PREFIX/bin/termux-style) && (-d $PREFIX/share/termux-style) ]]; then
		{ echo; echo "    ${BLUE}[${RED}!${BLUE}] ${MAGENTA}termux-style ${GREEN}is already installed."; }
		{ read -p "    ${BLUE}[${RED}?${BLUE}] ${ORANGE}Do you wanna re-install it? (y/n): ${GREEN}"; echo; }
		if [[ "$REPLY" =~ ^[y/Y]$ ]]; then
			install_tstyle
		else
			{ reset_color; exit; }
		fi
	else
		{ echo; install_tstyle; }
	fi
}

main
